### ISSUE TITLE
AwesomeAnimationHelper cannot be resolved 

### ISSUE THREAD

**Issue by Dil3mm4** [BootleggersROM/frameworks_base#23]
https://pastebin.com/Cc8i4gkY

**Comment by eldainosor** [comment]
Just when i pushed the fix, i got the notification of this. Issue has been solved now! Sorry for the derp

**Comment by Dil3mm4** [comment]
Can you please state the commit id? 
Thanks for the quick fix, derps happens :)

**Comment by eldainosor** [comment]
By just doing `repo sync --force-sync frameworks/base` you'll be fine ig. Just in case keep the `rm -rf frameworks/base` and then sync the project in case the previous one fails.

**Comment by Dil3mm4** [comment]
Yeah I know. 
I was just wondering what the fix was, since in the meanwhile I've reverted "aospextended" to "gzosp" utils for AnimationHelper :)

**Comment by eldainosor** [comment]
There's another big derp though, i'm on my way to fix it. So i'll push the fix dirty and then make it clean. Also, if after all this mess you made your device boot, please let us know on [our telegram chat](t.me/keepthebootleg)
