### ISSUE TITLE
lock screen blackout 

### ISSUE THREAD

**Issue by KhanStan99** [BootleggersROM/frameworks_base#62]
after opening the lock its just showing black screen and device is again getting locked

**Comment by dinosnore1** [comment]
@KhanStan99 Can you send us:
 1. A logcat (just use del.dog and paste the link here)
 2. Your device name
 3. The Bootleggers build number from Settings->About phone?

**Comment by KhanStan99** [comment]
> @KhanStan99 Can you send us:
> 
> 1. A logcat (just use del.dog and paste the link here)
> 2. Your device name
> 3. The Bootleggers build number from Settings->About phone?

**Comment by aarish124** [comment]
@KhanStan99 Kek
